// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCeAKRrtKeCkYbo9qDjqncc3Wmh_r9y4s4",
    authDomain: "hydrosafe01-dd126.firebaseapp.com",
    databaseURL:
        "https://hydrosafe01-dd126-default-rtdb.asia-southeast1.firebasedatabase.app",
    projectId: "hydrosafe01-dd126",
    storageBucket: "hydrosafe01-dd126.firebasestorage.app",
    messagingSenderId: "58159280734",
    appId: "1:58159280734:web:95e3df5d9b6381fcfbfacf",
    measurementId: "G-PDS4HHZ7EH",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyCeAKRrtKeCkYbo9qDjqncc3Wmh_r9y4s4",
    authDomain: "hydrosafe01-dd126.firebaseapp.com",
    databaseURL:
        "https://hydrosafe01-dd126-default-rtdb.asia-southeast1.firebasedatabase.app",
    projectId: "hydrosafe01-dd126",
    storageBucket: "hydrosafe01-dd126.firebasestorage.app",
    messagingSenderId: "58159280734",
    appId: "1:58159280734:web:95e3df5d9b6381fcfbfacf",
    measurementId: "G-PDS4HHZ7EH",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyCeAKRrtKeCkYbo9qDjqncc3Wmh_r9y4s4",
    authDomain: "hydrosafe01-dd126.firebaseapp.com",
    databaseURL:
        "https://hydrosafe01-dd126-default-rtdb.asia-southeast1.firebasedatabase.app",
    projectId: "hydrosafe01-dd126",
    storageBucket: "hydrosafe01-dd126.firebasestorage.app",
    messagingSenderId: "58159280734",
    appId: "1:58159280734:web:95e3df5d9b6381fcfbfacf",
    measurementId: "G-PDS4HHZ7EH",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyCeAKRrtKeCkYbo9qDjqncc3Wmh_r9y4s4",
    authDomain: "hydrosafe01-dd126.firebaseapp.com",
    databaseURL:
        "https://hydrosafe01-dd126-default-rtdb.asia-southeast1.firebasedatabase.app",
    projectId: "hydrosafe01-dd126",
    storageBucket: "hydrosafe01-dd126.firebasestorage.app",
    messagingSenderId: "58159280734",
    appId: "1:58159280734:web:95e3df5d9b6381fcfbfacf",
    measurementId: "G-PDS4HHZ7EH",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyCeAKRrtKeCkYbo9qDjqncc3Wmh_r9y4s4",
    authDomain: "hydrosafe01-dd126.firebaseapp.com",
    databaseURL:
        "https://hydrosafe01-dd126-default-rtdb.asia-southeast1.firebasedatabase.app",
    projectId: "hydrosafe01-dd126",
    storageBucket: "hydrosafe01-dd126.firebasestorage.app",
    messagingSenderId: "58159280734",
    appId: "1:58159280734:web:95e3df5d9b6381fcfbfacf",
    measurementId: "G-PDS4HHZ7EH",
  );
}
